.class public final Lcom/discord/restapi/RestAPIParams;
.super Ljava/lang/Object;
.source "RestAPIParams.kt"


# annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lcom/discord/restapi/RestAPIParams$ApplicationCommand;,
        Lcom/discord/restapi/RestAPIParams$ModalInteraction;,
        Lcom/discord/restapi/RestAPIParams$ModalInteractionData;,
        Lcom/discord/restapi/RestAPIParams$ModalInteractionDataComponent;,
        Lcom/discord/restapi/RestAPIParams$InviteCode;,
        Lcom/discord/restapi/RestAPIParams$AuthRegister;,
        Lcom/discord/restapi/RestAPIParams$AuthRegisterPhone;,
        Lcom/discord/restapi/RestAPIParams$AuthLogin;,
        Lcom/discord/restapi/RestAPIParams$RemoteAuthInitialize;,
        Lcom/discord/restapi/RestAPIParams$RemoteAuthFinish;,
        Lcom/discord/restapi/RestAPIParams$RemoteAuthCancel;,
        Lcom/discord/restapi/RestAPIParams$TextChannel;,
        Lcom/discord/restapi/RestAPIParams$TopicalChannel;,
        Lcom/discord/restapi/RestAPIParams$VoiceChannel;,
        Lcom/discord/restapi/RestAPIParams$ThreadCreationSettings;,
        Lcom/discord/restapi/RestAPIParams$ThreadSettings;,
        Lcom/discord/restapi/RestAPIParams$ChannelMessagesAck;,
        Lcom/discord/restapi/RestAPIParams$GuildFeatureAck;,
        Lcom/discord/restapi/RestAPIParams$ChannelPermissionOverwrites;,
        Lcom/discord/restapi/RestAPIParams$ChannelPosition;,
        Lcom/discord/restapi/RestAPIParams$ComponentInteraction;,
        Lcom/discord/restapi/RestAPIParams$ComponentInteractionData;,
        Lcom/discord/restapi/RestAPIParams$Consents;,
        Lcom/discord/restapi/RestAPIParams$CreateChannel;,
        Lcom/discord/restapi/RestAPIParams$CreateGuild;,
        Lcom/discord/restapi/RestAPIParams$CreateGuildFromTemplate;,
        Lcom/discord/restapi/RestAPIParams$CreateGuildChannel;,
        Lcom/discord/restapi/RestAPIParams$DeleteGuild;,
        Lcom/discord/restapi/RestAPIParams$EmptyBody;,
        Lcom/discord/restapi/RestAPIParams$EnableIntegration;,
        Lcom/discord/restapi/RestAPIParams$ForgotPassword;,
        Lcom/discord/restapi/RestAPIParams$GuildIntegration;,
        Lcom/discord/restapi/RestAPIParams$GuildMember;,
        Lcom/discord/restapi/RestAPIParams$GuildMemberDisconnect;,
        Lcom/discord/restapi/RestAPIParams$GuildMFA;,
        Lcom/discord/restapi/RestAPIParams$GroupDM;,
        Lcom/discord/restapi/RestAPIParams$Invite;,
        Lcom/discord/restapi/RestAPIParams$MFALogin;,
        Lcom/discord/restapi/RestAPIParams$AuthorizeIP;,
        Lcom/discord/restapi/RestAPIParams$Message;,
        Lcom/discord/restapi/RestAPIParams$GreetMessage;,
        Lcom/discord/restapi/RestAPIParams$Nick;,
        Lcom/discord/restapi/RestAPIParams$Phone;,
        Lcom/discord/restapi/RestAPIParams$Ring;,
        Lcom/discord/restapi/RestAPIParams$Thumbnail;,
        Lcom/discord/restapi/RestAPIParams$Role;,
        Lcom/discord/restapi/RestAPIParams$UpdateGuild;,
        Lcom/discord/restapi/RestAPIParams$MemberVerificationForm;,
        Lcom/discord/restapi/RestAPIParams$BanGuildMember;,
        Lcom/discord/restapi/RestAPIParams$DisableGuildCommunication;,
        Lcom/discord/restapi/RestAPIParams$PruneGuild;,
        Lcom/discord/restapi/RestAPIParams$UserAgreements;,
        Lcom/discord/restapi/RestAPIParams$UserDevices;,
        Lcom/discord/restapi/RestAPIParams$UserGuildSettings;,
        Lcom/discord/restapi/RestAPIParams$ChannelVoiceStateUpdate;,
        Lcom/discord/restapi/RestAPIParams$UserInfo;,
        Lcom/discord/restapi/RestAPIParams$UserNoteUpdate;,
        Lcom/discord/restapi/RestAPIParams$UserSettings;,
        Lcom/discord/restapi/RestAPIParams$UserSettingsCustomStatus;,
        Lcom/discord/restapi/RestAPIParams$UserRelationship;,
        Lcom/discord/restapi/RestAPIParams$UserBulkRelationship;,
        Lcom/discord/restapi/RestAPIParams$Report;,
        Lcom/discord/restapi/RestAPIParams$TransferGuildOwnership;,
        Lcom/discord/restapi/RestAPIParams$VanityUrl;,
        Lcom/discord/restapi/RestAPIParams$VerificationPhoneCode;,
        Lcom/discord/restapi/RestAPIParams$VerificationCode;,
        Lcom/discord/restapi/RestAPIParams$VerificationCodeOnly;,
        Lcom/discord/restapi/RestAPIParams$VerificationCodeResend;,
        Lcom/discord/restapi/RestAPIParams$DeletePhone;,
        Lcom/discord/restapi/RestAPIParams$CaptchaCode;,
        Lcom/discord/restapi/RestAPIParams$ConnectedAccount;,
        Lcom/discord/restapi/RestAPIParams$ConnectedAccountContacts;,
        Lcom/discord/restapi/RestAPIParams$ConnectedAccountNameOnly;,
        Lcom/discord/restapi/RestAPIParams$UploadContacts;,
        Lcom/discord/restapi/RestAPIParams$ContactEntry;,
        Lcom/discord/restapi/RestAPIParams$ConnectionState;,
        Lcom/discord/restapi/RestAPIParams$PostGuildEmoji;,
        Lcom/discord/restapi/RestAPIParams$PatchGuildEmoji;,
        Lcom/discord/restapi/RestAPIParams$EnableMFA;,
        Lcom/discord/restapi/RestAPIParams$UpdateSubscription;,
        Lcom/discord/restapi/RestAPIParams$DisableAccount;,
        Lcom/discord/restapi/RestAPIParams$ActivateMfaSMS;,
        Lcom/discord/restapi/RestAPIParams$OAuth2Authorize;,
        Lcom/discord/restapi/RestAPIParams$GenerateGiftCode;,
        Lcom/discord/restapi/RestAPIParams$GuildBoosting;,
        Lcom/discord/restapi/RestAPIParams$ChannelFollowerPost;,
        Lcom/discord/restapi/RestAPIParams$InvoicePreviewBody;,
        Lcom/discord/restapi/RestAPIParams$VerifyPurchaseTokenBody;,
        Lcom/discord/restapi/RestAPIParams$VerifyPurchaseResponse;,
        Lcom/discord/restapi/RestAPIParams$DowngradeSubscriptionBody;,
        Lcom/discord/restapi/RestAPIParams$PurchaseMetadataBody;,
        Lcom/discord/restapi/RestAPIParams$ThreadMemberSettings;,
        Lcom/discord/restapi/RestAPIParams$StartStageInstanceBody;,
        Lcom/discord/restapi/RestAPIParams$UpdateStageInstanceBody;,
        Lcom/discord/restapi/RestAPIParams$LeaveGuildBody;,
        Lcom/discord/restapi/RestAPIParams$VerifyEmail;,
        Lcom/discord/restapi/RestAPIParams$VerifyEmailCode;,
        Lcom/discord/restapi/RestAPIParams$HubWaitlist;,
        Lcom/discord/restapi/RestAPIParams$AddServerBody;,
        Lcom/discord/restapi/RestAPIParams$CreateGuildScheduledEventBody;,
        Lcom/discord/restapi/RestAPIParams$UpdateGuildScheduledEventBody;,
        Lcom/discord/restapi/RestAPIParams$CreateGuildRoleSubscriptionGroupListing;,
        Lcom/discord/restapi/RestAPIParams$UpdateGuildRoleSubscriptionGroupListing;,
        Lcom/discord/restapi/RestAPIParams$CreateGuildRoleSubscriptionTierListing;,
        Lcom/discord/restapi/RestAPIParams$UpdateGuildRoleSubscriptionTierListing;,
        Lcom/discord/restapi/RestAPIParams$UpdateGuildRoleSubscriptionTierFreeTrial;,
        Lcom/discord/restapi/RestAPIParams$UserEmailConfirmCode;,
        Lcom/discord/restapi/RestAPIParams$GetForumPostData;
    }
.end annotation

.annotation runtime Lkotlin/Metadata;
    bv = {
        0x1,
        0x0,
        0x3
    }
    d1 = {
        "\u0000\u000c\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\u0008o\u0018\u00002\u00020\u0001:l\u0004\u0005\u0006\u0007\u0008\t\n\u000b\u000c\r\u000e\u000f\u0010\u0011\u0012\u0013\u0014\u0015\u0016\u0017\u0018\u0019\u001a\u001b\u001c\u001d\u001e\u001f !\"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnoB\u0007\u00a2\u0006\u0004\u0008\u0002\u0010\u0003\u00a8\u0006p"
    }
    d2 = {
        "Lcom/discord/restapi/RestAPIParams;",
        "",
        "<init>",
        "()V",
        "ActivateMfaSMS",
        "AddServerBody",
        "ApplicationCommand",
        "AuthLogin",
        "AuthRegister",
        "AuthRegisterPhone",
        "AuthorizeIP",
        "BanGuildMember",
        "CaptchaCode",
        "ChannelFollowerPost",
        "ChannelMessagesAck",
        "ChannelPermissionOverwrites",
        "ChannelPosition",
        "ChannelVoiceStateUpdate",
        "ComponentInteraction",
        "ComponentInteractionData",
        "ConnectedAccount",
        "ConnectedAccountContacts",
        "ConnectedAccountNameOnly",
        "ConnectionState",
        "Consents",
        "ContactEntry",
        "CreateChannel",
        "CreateGuild",
        "CreateGuildChannel",
        "CreateGuildFromTemplate",
        "CreateGuildRoleSubscriptionGroupListing",
        "CreateGuildRoleSubscriptionTierListing",
        "CreateGuildScheduledEventBody",
        "DeleteGuild",
        "DeletePhone",
        "DisableAccount",
        "DisableGuildCommunication",
        "DowngradeSubscriptionBody",
        "EmptyBody",
        "EnableIntegration",
        "EnableMFA",
        "ForgotPassword",
        "GenerateGiftCode",
        "GetForumPostData",
        "GreetMessage",
        "GroupDM",
        "GuildBoosting",
        "GuildFeatureAck",
        "GuildIntegration",
        "GuildMFA",
        "GuildMember",
        "GuildMemberDisconnect",
        "HubWaitlist",
        "Invite",
        "InviteCode",
        "InvoicePreviewBody",
        "LeaveGuildBody",
        "MFALogin",
        "MemberVerificationForm",
        "Message",
        "ModalInteraction",
        "ModalInteractionData",
        "ModalInteractionDataComponent",
        "Nick",
        "OAuth2Authorize",
        "PatchGuildEmoji",
        "Phone",
        "PostGuildEmoji",
        "PruneGuild",
        "PurchaseMetadataBody",
        "RemoteAuthCancel",
        "RemoteAuthFinish",
        "RemoteAuthInitialize",
        "Report",
        "Ring",
        "Role",
        "StartStageInstanceBody",
        "TextChannel",
        "ThreadCreationSettings",
        "ThreadMemberSettings",
        "ThreadSettings",
        "Thumbnail",
        "TopicalChannel",
        "TransferGuildOwnership",
        "UpdateGuild",
        "UpdateGuildRoleSubscriptionGroupListing",
        "UpdateGuildRoleSubscriptionTierFreeTrial",
        "UpdateGuildRoleSubscriptionTierListing",
        "UpdateGuildScheduledEventBody",
        "UpdateStageInstanceBody",
        "UpdateSubscription",
        "UploadContacts",
        "UserAgreements",
        "UserBulkRelationship",
        "UserDevices",
        "UserEmailConfirmCode",
        "UserGuildSettings",
        "UserInfo",
        "UserNoteUpdate",
        "UserRelationship",
        "UserSettings",
        "UserSettingsCustomStatus",
        "VanityUrl",
        "VerificationCode",
        "VerificationCodeOnly",
        "VerificationCodeResend",
        "VerificationPhoneCode",
        "VerifyEmail",
        "VerifyEmailCode",
        "VerifyPurchaseResponse",
        "VerifyPurchaseTokenBody",
        "VoiceChannel",
        "restapi_release"
    }
    k = 0x1
    mv = {
        0x1,
        0x4,
        0x2
    }
.end annotation


# direct methods
.method public constructor <init>()V
    .locals 0

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method
