.class public final Lcom/discord/utilities/UtcDateTimeParceler;
.super Ljava/lang/Object;
.source "Parcelers.kt"

# interfaces
.implements Ls/b/a;


# annotations
.annotation system Ldalvik/annotation/Signature;
    value = {
        "Ljava/lang/Object;",
        "Ls/b/a<",
        "Lcom/discord/api/utcdatetime/UtcDateTime;",
        ">;"
    }
.end annotation

.annotation runtime Lkotlin/Metadata;
    bv = {
        0x1,
        0x0,
        0x3
    }
    d1 = {
        "\u0000\"\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0008\u0003\n\u0002\u0010\u0008\n\u0000\n\u0002\u0010\u0002\n\u0002\u0008\u0005\u0008\u00c6\u0002\u0018\u00002\u0008\u0012\u0004\u0012\u00020\u00020\u0001B\t\u0008\u0002\u00a2\u0006\u0004\u0008\u000c\u0010\rJ\u0017\u0010\u0005\u001a\u00020\u00022\u0006\u0010\u0004\u001a\u00020\u0003H\u0016\u00a2\u0006\u0004\u0008\u0005\u0010\u0006J#\u0010\n\u001a\u00020\t*\u00020\u00022\u0006\u0010\u0004\u001a\u00020\u00032\u0006\u0010\u0008\u001a\u00020\u0007H\u0016\u00a2\u0006\u0004\u0008\n\u0010\u000b\u00a8\u0006\u000e"
    }
    d2 = {
        "Lcom/discord/utilities/UtcDateTimeParceler;",
        "Ls/b/a;",
        "Lcom/discord/api/utcdatetime/UtcDateTime;",
        "Landroid/os/Parcel;",
        "parcel",
        "create",
        "(Landroid/os/Parcel;)Lcom/discord/api/utcdatetime/UtcDateTime;",
        "",
        "flags",
        "",
        "write",
        "(Lcom/discord/api/utcdatetime/UtcDateTime;Landroid/os/Parcel;I)V",
        "<init>",
        "()V",
        "app_productionGoogleRelease"
    }
    k = 0x1
    mv = {
        0x1,
        0x4,
        0x2
    }
.end annotation


# static fields
.field public static final INSTANCE:Lcom/discord/utilities/UtcDateTimeParceler;


# direct methods
.method public static constructor <clinit>()V
    .locals 1

    .line 1
    new-instance v0, Lcom/discord/utilities/UtcDateTimeParceler;

    invoke-direct {v0}, Lcom/discord/utilities/UtcDateTimeParceler;-><init>()V

    sput-object v0, Lcom/discord/utilities/UtcDateTimeParceler;->INSTANCE:Lcom/discord/utilities/UtcDateTimeParceler;

    return-void
.end method

.method private constructor <init>()V
    .locals 0

    .line 1
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    return-void
.end method


# virtual methods
.method public create(Landroid/os/Parcel;)Lcom/discord/api/utcdatetime/UtcDateTime;
    .locals 3

    const-string v0, "parcel"

    invoke-static {p1, v0}, Ld0/z/d/m;->checkNotNullParameter(Ljava/lang/Object;Ljava/lang/String;)V

    .line 2
    new-instance v0, Lcom/discord/api/utcdatetime/UtcDateTime;

    invoke-virtual {p1}, Landroid/os/Parcel;->readLong()J

    move-result-wide v1

    invoke-direct {v0, v1, v2}, Lcom/discord/api/utcdatetime/UtcDateTime;-><init>(J)V

    return-object v0
.end method

.method public bridge synthetic create(Landroid/os/Parcel;)Ljava/lang/Object;
    .locals 0

    .line 1
    invoke-virtual {p0, p1}, Lcom/discord/utilities/UtcDateTimeParceler;->create(Landroid/os/Parcel;)Lcom/discord/api/utcdatetime/UtcDateTime;

    move-result-object p1

    return-object p1
.end method

.method public newArray(I)[Lcom/discord/api/utcdatetime/UtcDateTime;
    .locals 1

    const-string/jumbo p1, "this"

    .line 1
    invoke-static {p0, p1}, Ld0/z/d/m;->checkNotNullParameter(Ljava/lang/Object;Ljava/lang/String;)V

    .line 2
    new-instance p1, Ld0/j;

    const-string v0, "Generated by Android Extensions automatically"

    invoke-direct {p1, v0}, Ld0/j;-><init>(Ljava/lang/String;)V

    throw p1
.end method

.method public bridge synthetic newArray(I)[Ljava/lang/Object;
    .locals 0

    .line 3
    invoke-virtual {p0, p1}, Lcom/discord/utilities/UtcDateTimeParceler;->newArray(I)[Lcom/discord/api/utcdatetime/UtcDateTime;

    move-result-object p1

    return-object p1
.end method

.method public write(Lcom/discord/api/utcdatetime/UtcDateTime;Landroid/os/Parcel;I)V
    .locals 2

    const-string p3, "$this$write"

    invoke-static {p1, p3}, Ld0/z/d/m;->checkNotNullParameter(Ljava/lang/Object;Ljava/lang/String;)V

    const-string p3, "parcel"

    invoke-static {p2, p3}, Ld0/z/d/m;->checkNotNullParameter(Ljava/lang/Object;Ljava/lang/String;)V

    .line 2
    invoke-virtual {p1}, Lcom/discord/api/utcdatetime/UtcDateTime;->g()J

    move-result-wide v0

    invoke-virtual {p2, v0, v1}, Landroid/os/Parcel;->writeLong(J)V

    return-void
.end method

.method public bridge synthetic write(Ljava/lang/Object;Landroid/os/Parcel;I)V
    .locals 0

    .line 1
    check-cast p1, Lcom/discord/api/utcdatetime/UtcDateTime;

    invoke-virtual {p0, p1, p2, p3}, Lcom/discord/utilities/UtcDateTimeParceler;->write(Lcom/discord/api/utcdatetime/UtcDateTime;Landroid/os/Parcel;I)V

    return-void
.end method
